export const technologies = [
  { 
    id: 'aws', 
    slug: 'aws', 
    title: 'AWS', 
    shortName: 'AWS',
    fullName: 'Amazon Web Services',
    description: 'Cloud compute (EC2), IAM security, S3 storage, VPC networking, ALB load balancing, and ECS container orchestration.', 
    icon: 'aws', 
    color: '#FF9900', 
    lightBg: 'bg-amber-50',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-700',
    badgeBg: 'bg-amber-100 text-amber-800 border-amber-300',
    officialDocUrl: 'https://docs.aws.amazon.com/'
  },
  { 
    id: 'docker', 
    slug: 'docker', 
    title: 'Docker', 
    shortName: 'Docker',
    fullName: 'Docker Container Platform',
    description: 'Containerization, Dockerfile optimization, multi-stage builds, volumes, networking, and Docker Compose orchestration.', 
    icon: 'docker', 
    color: '#2496ED', 
    lightBg: 'bg-sky-50',
    borderColor: 'border-sky-200',
    textColor: 'text-sky-700',
    badgeBg: 'bg-sky-100 text-sky-800 border-sky-300',
    officialDocUrl: 'https://docs.docker.com/'
  },
  { 
    id: 'kubernetes', 
    slug: 'kubernetes', 
    title: 'Kubernetes', 
    shortName: 'K8s',
    fullName: 'Kubernetes Orchestration',
    description: 'Cluster management, Pods, Deployments, Services, Ingress controllers, ConfigMaps, Secrets, and StatefulSets.', 
    icon: 'kubernetes', 
    color: '#326CE5', 
    lightBg: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-700',
    badgeBg: 'bg-blue-100 text-blue-800 border-blue-300',
    officialDocUrl: 'https://kubernetes.io/docs/'
  },
  { 
    id: 'linux', 
    slug: 'linux', 
    title: 'Linux', 
    shortName: 'Linux',
    fullName: 'Linux System Administration',
    description: 'CLI commands, file permissions, process management, shell scripting (bash), networking tools, and systemd services.', 
    icon: 'linux', 
    color: '#2D3748', 
    lightBg: 'bg-slate-100',
    borderColor: 'border-slate-300',
    textColor: 'text-slate-800',
    badgeBg: 'bg-slate-200 text-slate-900 border-slate-300',
    officialDocUrl: 'https://www.kernel.org/doc/html/latest/'
  },
  { 
    id: 'git', 
    slug: 'git', 
    title: 'Git', 
    shortName: 'Git',
    fullName: 'Git Version Control System',
    description: 'Distributed version control, branching strategies, interactive rebasing, cherry-picking, and GitHub PR workflows.', 
    icon: 'git', 
    color: '#F05032', 
    lightBg: 'bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-orange-700',
    badgeBg: 'bg-orange-100 text-orange-800 border-orange-300',
    officialDocUrl: 'https://git-scm.com/doc'
  },
  { 
    id: 'terraform', 
    slug: 'terraform', 
    title: 'Terraform', 
    shortName: 'Terraform',
    fullName: 'HashiCorp Terraform IaC',
    description: 'Infrastructure as Code (IaC), HCL syntax, resource providers, state management, reusable modules, and backends.', 
    icon: 'terraform', 
    color: '#844FBA', 
    lightBg: 'bg-purple-50',
    borderColor: 'border-purple-200',
    textColor: 'text-purple-700',
    badgeBg: 'bg-purple-100 text-purple-800 border-purple-300',
    officialDocUrl: 'https://developer.hashicorp.com/terraform/docs'
  },
];
